ARG KEYCLOAK_IMAGE=quay.io/keycloak/keycloak:latest
FROM ${KEYCLOAK_IMAGE}

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_HTTP_ENABLED=true

COPY keycloak/mam-dev-realm.json /opt/keycloak/data/import/mam-dev-realm.json

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start-dev", "--import-realm", "--bootstrap-admin-username=admin", "--bootstrap-admin-password=Admin000"]
